ackermann_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : drive
        timeout : 0.2
        priority: 200
      joystick:
        topic   : teleop
        timeout : 0.2
        priority: 10
    locks:
      autonomous:
        topic   : autonomous_lock
        timeout : 0.0
        priority: 100